name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ upstream-updated ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Checkout parent POM
        uses: actions/checkout@v4
        with:
          repository: rspereiratech/openapi-generator-parent
          path: openapi-generator-parent
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install parent POM
        run: mvn install -f openapi-generator-parent/pom.xml -DskipTests

      - name: Checkout core
        uses: actions/checkout@v4
        with:
          repository: rspereiratech/openapi-generator-core
          path: openapi-generator-core
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install core
        run: mvn install -f openapi-generator-core/pom.xml -DskipTests

      - name: Checkout plugin
        uses: actions/checkout@v4
        with:
          repository: rspereiratech/openapi-generator-maven-plugin
          path: openapi-generator-maven-plugin
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install plugin
        run: mvn install -f openapi-generator-maven-plugin/pom.xml -DskipTests

      - name: Build and generate spec
        run: mvn process-classes
